language: objective-c
osx_image: xcode9.3
podfile: FSRoutesProject/Podfile
before_install:
  - gem install xcpretty
script:
  - ruby run-tests.rb
after_success:
  - bash <(curl -s https://codecov.io/bash)

  