language: objective-c
osx_image: xcode9.3
podfile: FSRoutesProject/Podfile
script:
  xctool -workspace FSRoutesProject/FSRoutesProject.xcworkspace -scheme FSRoutesProjectTests run-tests -test-sdk iphonesimulator11.4
after_success:
  - bash <(curl -s https://codecov.io/bash)

  