language: objective-c
osx_image: xcode9.3
podfile: FSRoutesProject/Podfile
script:
  - xcodebuild -workspace FSRoutesProject/FSRoutesProject.xcworkspace -scheme FSRoutesProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)