language: objective-c
osx_image: xcode9.3
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - pod install
  - xctool -workspace FSRoutesProject/FSRoutesProject.xcworkspace -scheme FSRoutesProjectTests run-tests -test-sdk iphonesimulator11.4 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)

  