platform :ios, '9.0'

target 'FSRoutesProject' do
    pod 'FSRoutes', :path => '../'
end

target 'FSRoutesProjectTests' do
    pod 'Expecta'
    pod 'FSRoutes', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each_with_index do |target, idx|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end

